apollo-server/index
GraphQL-China/tools-docs pull request #25
Opened 2017-09-02 14:21 UTC by ydfzgyj

之前 index 那个文件的“生产级别的”修改也偷懒扔到这个 PR 里了

2017-09-04 00:54 UTC, jonirrings approved these changes
没有问题

2017-09-04 00:54 UTC, jonirrings commented
query batch 这个现在有木有定案的翻译啊，貌似已经引入到relay的草案了。

2017-09-04 07:17 UTC, ydfzgyj commented
> query batch 这个现在有木有定案的翻译啊

查询批处理？批处理查询？

2017-09-04 08:00 UTC, jonirrings commented
或者批量查询？

2017-09-04 08:50 UTC, ydfzgyj commented
query batch 和 batch query 是一样的吗？有点迷

2017-09-04 08:59 UTC, jonirrings commented
这个方案是Apollo提给GraphQL组的，然后relay组先整合了。要不去apollo的medium上看看，貌似query batch 和 batch query 是一样的:joy:

2017-09-15 08:58 UTC, linonetwo requested changes

2017-09-15 08:58 UTC, linonetwo commented on tools/apollo-server/index.md
> +- Apollo Server 支持 [查询批处理](https://medium.com/apollo-stack/query-batching-in-apollo-63acfd859862)，可以有助于减少服务器的负载。
批处理毕竟是已有技术名词，得换一个，「批量查询」也行，不过我觉得「查询合并」更好一些，因为批量 xx 会有一种一个个执行的流水线的感觉，就像批处理程序那样。
还有 batched query 是名词，应该是「合并的查询」

2017-09-15 09:27 UTC, ydfzgyj commented on tools/apollo-server/index.md
> +- Apollo Server 支持 [查询批处理](https://medium.com/apollo-stack/query-batching-in-apollo-63acfd859862)，可以有助于减少服务器的负载。
可以的，“查询合并”确实更好一点

2017-09-17 11:15 UTC, linonetwo approved these changes

2017-09-17 11:15 UTC, merged